Muq 34
genny-project/qwanda pull request #169
Opened 2022-08-22 07:27 UTC by mnzit

2022-08-22 07:27 UTC, github-gada commented
Author is not in whitelist. Can one of the admins verify this patch?

2022-08-23 05:35 UTC, varunshastry requested changes

2022-08-23 05:35 UTC, varunshastry commented on src/main/java/life/genny/qwanda/converter/MinIOConverter.java
> +            log.info("####### Fetching from MinIO");
####### to be removed

2022-08-23 05:35 UTC, varunshastry commented on src/main/java/life/genny/qwanda/util/minio/Minio.java
> +        if (uploadFile(REALM.concat("/") + "public", file.uploadedFileName(), file.fileName())) {
Extract the function call to local variable for better clarity.

2022-08-23 05:35 UTC, varunshastry commented on src/main/java/life/genny/qwanda/util/minio/Minio.java
> +        if (uploadFile(userUUID.toString(), file.uploadedFileName(), randomUUID.toString())) {
Extract the function call to local variable for better clarity.

2022-08-23 05:35 UTC, varunshastry commented on src/main/java/life/genny/qwanda/util/minio/Minio.java
> +            e.printStackTrace();
Will printstacktrace log the exception to log file as "INFO"? Do we want to add specific message?

2022-08-24 03:17 UTC, varunshastry requested changes

2022-08-24 03:17 UTC, varunshastry commented on src/main/java/life/genny/qwanda/util/minio/MinIOEnvironmentVariable.java
> +        Optional.ofNullable(System.getenv("MINIO_SERVER_URL"));
Extract to "Constants"

2022-08-24 08:37 UTC, merged