MUQ-34 MinIO valueString feature
genny-project/qwanda pull request #170
Opened 2022-08-24 11:45 UTC by mnzit

2022-08-24 11:45 UTC, github-gada commented
Author is not in whitelist. Can one of the admins verify this patch?

2022-08-24 22:58 UTC, weslyvo81 approved these changes
LGTM. need to test minio version

2022-08-29 02:34 UTC, varunshastry requested changes

2022-08-29 02:34 UTC, varunshastry commented on src/main/java/life/genny/qwanda/constant/MinIOConstant.java
> +                Optional.ofNullable(System.getenv("MINIO_SERVER_URL"));
Extract to constants

2022-09-08 04:46 UTC, varunshastry requested changes

2022-09-08 04:46 UTC, varunshastry commented on src/main/java/life/genny/qwanda/constant/MinIOConstant.java
> +                Optional.ofNullable(System.getenv("MINIO_SERVER_URL"));
Strings to be extracted to constants

2022-09-08 04:46 UTC, varunshastry commented on src/main/java/life/genny/qwanda/converter/MinIOConverter.java
> +                return "Error Occurred";
Throw an exception instead of returning such a string - say, "EntityAttributeConversionException"

2022-09-08 04:46 UTC, varunshastry commented on src/main/java/life/genny/qwanda/util/minio/Minio.java
> +    private static String REALM = Optional.ofNullable(System.getenv("REALM")).orElse("internmatch");
Strings to be extracted to constants

2022-09-08 04:48 UTC, varunshastry requested changes

2022-09-08 04:48 UTC, varunshastry commented on pom.xml
> +		<minio.version>6.0.2</minio.version>
Latest version is 8.4.3. Any reason why 6.0.2 is used?

2022-10-11 10:44 UTC, varunshastry approved these changes

2022-10-11 10:45 UTC, merged